CREATE TABLE IMS_CONTRACT_INFO(
    ID NUMBER NOT NULL,
    REFNO VARCHAR2(30),
    CONTRACTCODE VARCHAR2(100),
    MAMOUNT  NUMBER(21,6),
    DTINPUT  DATE,
    DTMODIFY  DATE,
    MESSAGEBODY CLOB,
    PRIMARY KEY (ID)
);


COMMENT ON TABLE IMS_CONTRACT_INFO IS 'IMS合同信息记录表';
COMMENT ON COLUMN IMS_CONTRACT_INFO.ID IS '流水号';
COMMENT ON COLUMN IMS_CONTRACT_INFO.REFNO IS '付款单号';
COMMENT ON COLUMN IMS_CONTRACT_INFO.CONTRACTCODE IS '合同编号';
COMMENT ON COLUMN IMS_CONTRACT_INFO.MAMOUNT IS '合同金额';
COMMENT ON COLUMN IMS_CONTRACT_INFO.DTINPUT IS '录入时间';
COMMENT ON COLUMN IMS_CONTRACT_INFO.DTMODIFY IS '修改时间';
COMMENT ON COLUMN IMS_CONTRACT_INFO.MESSAGEBODY IS '完整的合同信息';

-- 新建序列 
CREATE SEQUENCE SEQ_IMS_CONTRACT_INFO --序列名称(seq_表名[超过30个字符，去掉表名前缀])
INCREMENT BY 1 --每次增长
START WITH 1 --起始值
MAXVALUE 99999999999999999 --最大值
MINVALUE 1  --最小值
CYCLE  --到达最大值处理(循环)
CACHE 20 --缓存序列大小(一次性生成)
ORDER;
